#!/bin/bash

set -eu

# s3simple is a small, simple bash s3 client with minimal dependencies.
# See http://github.com/paulhammond/s3simple for documentation and licence.

_s3simple_hex() {
	od -A n -t x1 | tr -d ' \n\t'
}

_s3simple_hmac_hex() {
	local hexkey="$1"
	local data="$2"
	echo -n "$data" | openssl dgst -sha256 -mac HMAC -macopt hexkey:"$hexkey" -binary | _s3simple_hex
}

s3simple() {
	local command="$1"
	local url="$2"
	local file="${3:--}"

	if [ "${url:0:5}" != "s3://" ]; then
		echo "Need an s3 url"
		return 1
	fi
	local path="${url:5}"

	if [ -z "${AWS_ACCESS_KEY_ID-}" ]; then
		echo "Need AWS_ACCESS_KEY_ID to be set"
		return 1
	fi

	if [ -z "${AWS_SECRET_ACCESS_KEY-}" ]; then
		echo "Need AWS_SECRET_ACCESS_KEY to be set"
		return 1
	fi

	local region="${AWS_DEFAULT_REGION:-${AWS_REGION:-us-east-1}}"

	local method md5 args listing=""
	case "$command" in
	get)
		method="GET"
		md5=""
		args=(-o "$file")
		;;
	head)
		method="HEAD"
		md5=""
		args=(-I)
		;;
	put)
		method="PUT"
		if [ ! -f "$file" ]; then
			echo "file not found"
			exit 1
		fi
		md5="$(openssl md5 -binary "$file" | openssl base64)"
		args=(-T "$file" -H "Content-MD5: $md5")
		;;
	ls | ll)
		method="GET"
		md5=""
		args=()
		listing=1
		;;
	*)
		echo "Unsupported command"
		return 1
		;;
	esac

	local bucket key canonical_querystring=""
	if [ -n "$listing" ]; then
		if [[ "$path" == */* ]]; then
			bucket="${path%%/*}"
			canonical_querystring="list-type=2&prefix=${path#*/}"
		else
			bucket="$path"
			canonical_querystring="list-type=2"
		fi
		key=""
	else
		bucket="${path%%/*}"
		key="${path#*/}"
	fi

	local host canonical_uri
	if [ -n "${S3_ENDPOINT_URL-}" ]; then
		local endpoint="${S3_ENDPOINT_URL%/}"
		host="${endpoint#*://}"
		host="${host%%/*}"
		if [ -n "$listing" ]; then
			url="${endpoint}/${bucket}?${canonical_querystring}"
			canonical_uri="/${bucket}"
		else
			url="${endpoint}/${bucket}/${key}"
			canonical_uri="/${bucket}/${key}"
		fi
	elif [[ "$bucket" == *.* ]]; then
		# Bucket names with dots can't use virtual-hosted style (wildcard TLS cert
		# *.s3.amazonaws.com doesn't cover multi-label names like a.b.s3.amazonaws.com)
		host="s3.${region}.amazonaws.com"
		if [ -n "$listing" ]; then
			url="https://${host}/${bucket}?${canonical_querystring}"
			canonical_uri="/${bucket}"
		else
			url="https://${host}/${bucket}/${key}"
			canonical_uri="/${bucket}/${key}"
		fi
	else
		host="${bucket}.s3.amazonaws.com"
		if [ -n "$listing" ]; then
			url="https://${host}/?${canonical_querystring}"
			canonical_uri="/"
		else
			url="https://${host}/${key}"
			canonical_uri="/${key}"
		fi
	fi

	local amz_date
	amz_date="$(date -u '+%Y%m%dT%H%M%SZ')"
	local short_date="${amz_date:0:8}"

	local content_sha256="UNSIGNED-PAYLOAD"

	local canonical_headers signed_headers
	canonical_headers="host:${host}\nx-amz-content-sha256:${content_sha256}\nx-amz-date:${amz_date}"
	signed_headers="host;x-amz-content-sha256;x-amz-date"
	if [ -n "${AWS_SESSION_TOKEN-}" ]; then
		canonical_headers="${canonical_headers}\nx-amz-security-token:${AWS_SESSION_TOKEN}"
		signed_headers="${signed_headers};x-amz-security-token"
	fi

	local canonical_request
	printf -v canonical_request "%s\n%s\n%s\n%b\n\n%s\n%s" \
		"$method" \
		"$canonical_uri" \
		"$canonical_querystring" \
		"$canonical_headers" \
		"$signed_headers" \
		"$content_sha256"

	local canonical_request_hash
	canonical_request_hash=$(echo -n "$canonical_request" | openssl dgst -sha256 | sed 's/^.*= //')

	local credential_scope="${short_date}/${region}/s3/aws4_request"

	local string_to_sign
	printf -v string_to_sign "AWS4-HMAC-SHA256\n%s\n%s\n%s" \
		"$amz_date" \
		"$credential_scope" \
		"$canonical_request_hash"

	local kDate kRegion kService kSigning
	kDate=$(echo -n "$short_date" | openssl dgst -sha256 -hmac "AWS4${AWS_SECRET_ACCESS_KEY}" -binary | _s3simple_hex)
	kRegion=$(_s3simple_hmac_hex "$kDate" "$region")
	kService=$(_s3simple_hmac_hex "$kRegion" "s3")
	kSigning=$(_s3simple_hmac_hex "$kService" "aws4_request")

	local signature
	signature=$(echo -n "$string_to_sign" | openssl dgst -sha256 -mac HMAC -macopt hexkey:"$kSigning" | sed 's/^.*= //')

	local authorization="AWS4-HMAC-SHA256 Credential=${AWS_ACCESS_KEY_ID}/${credential_scope}, SignedHeaders=${signed_headers}, Signature=${signature}"

	args+=(
		-H "Host: ${host}"
		-H "x-amz-date: ${amz_date}"
		-H "x-amz-content-sha256: ${content_sha256}"
		-H "Authorization: ${authorization}"
	)

	if [ -n "${AWS_SESSION_TOKEN-}" ]; then
		args+=(-H "x-amz-security-token: ${AWS_SESSION_TOKEN}")
	fi

	if [ "$command" = "ll" ]; then
		curl "${args[@]}" -s -f "$url" | tr '<' '\n' | awk '
			function human(b) {
				if (b >= 1073741824) return sprintf("%.1f G", b/1073741824)
				if (b >= 1048576)    return sprintf("%.1f M", b/1048576)
				if (b >= 1024)       return sprintf("%.1f K", b/1024)
				return b "  "
			}
			/^Key>/          { gsub(/^Key>/, ""); key=$0 }
			/^LastModified>/ { gsub(/^LastModified>/, ""); mod=$0 }
			/^Size>/         { gsub(/^Size>/, ""); size=$0 }
			/^StorageClass>/ { gsub(/^StorageClass>/, ""); sc=$0 }
			/^\/Contents>/   { printf "%s  %6s  %-12s  %s\n", mod, human(size+0), sc, key }
		'
	elif [ "$command" = "ls" ]; then
		curl "${args[@]}" -s -f "$url" | grep -o '<Key>[^<]*</Key>' | sed 's/<[^>]*>//g'
	else
		curl "${args[@]}" -s -f "$url"
	fi
}

s3simple "$@"
